### ISSUE TITLE
prevent and remove duplicate certificate nodes arising from event attendance updates

### ISSUE THREAD

**Issue by anjirlly** [knieper/crltmich#8] opened 2016-01-11 19:23 UTC
Restoring lost functionality

1) PREVENT
When a certificate node already exists, and the event attendance is updated, don't let it create another certificate. 

Relevant field
field_certificate_source and field_certificate_source_id
The source is signup.
source_id is node number of event

2) REMOVE
Find nodes previously created in duplicate and eliminate them, with attention to any difference in workflow state among duplicated nodes. 

For example, if nodes that appear to be duplicates have different workflow states, then we'd need to discuss logic of which one to delete, but we note that all such nodes are expected to have the workflow state of approved.

**Comment by mbakewel** [comment] 2016-03-22 20:53
duplicate nodes are not being created - so that part is resolved. However, new certificate nodes are created with workflow state = 'New request = awaiting review" instead of "Approved" They are set to approved if the attendance is re-set to attended after the certificate node was created.

**Comment by knieper** [comment] 2016-03-24 19:23
I just did a test event, test sign up and then a test 'marked attended' and it gets set correctly. 

![image](https://cloud.githubusercontent.com/assets/812430/14028712/4574b254-f1d4-11e5-858d-bfd2aa9d669d.png)

I may be misunderstanding

**Comment by mbakewel** [comment] 2016-04-01 16:01
The issue is fixed. However, we (jeri and I ) both got a spinning blue "hourglass" when trying to make attendance in bulk on the node, see screenshot.
![image](https://cloud.githubusercontent.com/assets/5739661/14212544/7139b64a-f801-11e5-847a-9ab9e02a5a0e.png)

**Comment by knieper** [comment] 2016-04-04 16:54
Did it hang there forever? or was it momentary?

**Comment by mbakewel** [comment] 2016-04-05 13:50
forever! at least > 2-3 minutes. It did this for me and for Jeri.

On Mon, Apr 4, 2016 at 12:54 PM, Sharon Knieper notifications@github.com
wrote:

> Did it hang there forever? or was it momentary?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/knieper/crltmich/issues/8#issuecomment-205390711

## 

---

Meg Bakewell, Ph.D.
Assistant Director
Center for Research on Learning and Teaching (CRLT)

**Comment by knieper** [comment] 2016-05-12 21:30
Was never able to reproduce the hanging hourglass behavior. I wonder if it was connected to the issues seen with the white screen of death?. Closing until additional reports come in.

**Closed as completed by knieper** 2016-05-12 21:30 UTC
Labels: bug, question
